
model: 'efficientnetb0'
embedding_dim: 1280
pipeline: "triplet"
batch_size: 20
dataset_path: 'C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/renal-pathology-retrieval/data/02_data_split/train_data/'
save_file_path: 'C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/renal-pathology-retrieval/data_output/trained_embeddings/efficientnetb0_4096_triple.pickle'
