
model: 'efficientnetb0'
embedding_dim: 1280
pipeline: 0
train: False
batch_size: 128
dataset_path: 'C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/renal-pathology-retrieval/data/02_data_split/train_data/'
save_file_path: 'C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/renal-pathology-retrieval/evaluation/efficientnetb0_4096_pretrained_train.pickle'
model_state_dict_path: 'C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/renal-pathology-retrieval/data_output/checkpoints/efficientnetb0_triplet_2023-09-17-20-06-09/checkpoint.pth.tar'
