model: 'efficientnetb0_encoder'
embedding_dim: 12544
pipeline: 0
train: False
batch_size: 128
dataset_path: 'C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/renal-pathology-retrieval/data/03_test'
save_file_path: 'C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/renal-pathology-retrieval/evaluation/efficientnetb0_4096_autoencoder_test.pickle'
model_state_dict_path: 'C:/Users/Maods/Documents/Development/Mestrado/terumo/apps/renal-pathology-retrieval/data_output/checkpoints/efficientnetb0_encoder_autoencoder_2023-09-18-23-07-57/checkpoint.pth.tar'
